granian/server.py, src/tls.rs, tests/test_https.py
=> enhance HTTPS implementation

granian/_futures.py
As said in the following discussions:
https://github.com/emmett-framework/granian/discussions/30
Almost sure this optimization will make granian ASGI faster than uvicorn+uvloop+httptools+gunicorn (in local tests is)
PS the same improvement can be made in add_done_callback in `src/runtime.rs`, `src/generic.rs` and `src/lib.rs`
=> Performance improvement in futures handling

granian/wsgi.py
=> Fix WSGI environ optional items

src/asgi/io.rs, src/wsgi/http.rs
=> Fix response headers getting overwritten in ASGI, WSGI protocols

docs/spec/RSGI.md
=> Add rationale to RSGI spec

pyproject.toml
=> Relax `typer` dep version

granian/asgi.py, granian/cli.py, granian/server.py, granian/wsgi.py
=> Add `url-path-prefix` option

granian/cli.py, granian/server.py, pyproject.toml
=> Add `reload` option

granian/log.py, granian/server.py
=> Add `log_dictconfig` param to `Server`

granian/wsgi.py, src/wsgi/callbacks.rs, src/wsgi/http.rs, src/wsgi/types.rs, tests/apps/wsgi.py, tests/test_wsgi.py
=> add WSGI response body iteration

granian/asgi.py, src/asgi/errors.rs, src/asgi/io.rs, src/callbacks.rs
=> add ASGI response body streaming

granian/server.py, src/asgi/callbacks.rs, src/callbacks.rs, src/rsgi/callbacks.rs, src/rsgi/http.rs, src/rsgi/serve.rs
=> Allow to disable loop optimizations on RSGI workers

granian/server.py
=> lock number of workers to 1 on windows

granian/__main__.py
I've added the `__main__.py` file so `python -m granian` can be used.
=> add package entrypoint

granian/_granian.pyi, granian/asgi.py, granian/wsgi.py, src/asgi/types.rs, src/wsgi/serve.rs, src/wsgi/types.rs
=> Enhance scope allocs

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml, Cargo.lock, Makefile, pyproject.toml
I've included your updates in 0.6.1. All tests pass.
Close #136
=> Python 3.12

Cargo.lock, Cargo.toml, src/asgi/types.rs, src/rsgi/types.rs, src/wsgi/types.rs
=> Percent decode paths in scopes

granian/asgi.py, granian/server.py, src/asgi/types.rs, tests/apps/asgi.py, tests/test_asgi.py
=> Add support for ASGI lifespan state

granian/cli.py, granian/http.py, granian/server.py, src/asgi/serve.rs, src/conversion.rs, src/rsgi/serve.rs, src/workers.rs, src/wsgi/serve.rs
=> Expose HTTP options to Python

Cargo.lock, Cargo.toml, src/asgi/types.rs, src/callbacks.rs, src/runtime.rs
=> Drop `once_cell` crate dependency

src/callbacks.rs, src/runtime.rs
=> Allow cancel on `PyFutureAwaitable`

granian/cli.py, granian/server.py
=> Add workers respawn on failure

granian/server.py
=> Add HUP signal handling to gracefully respawn workers

src/asgi/io.rs
=> Add `code` item to `websocket.disconnect` event

docs/spec/RSGI.md, granian/_granian.pyi, src/asgi/types.rs, src/rsgi/types.rs, src/wsgi/types.rs, tests/apps/rsgi.py, tests/test_rsgi.py, tests/test_ws.py
=> Host header on HTTP/2

README.md, granian/cli.py, granian/server.py, pyproject.toml
=> Make the watchfiles dependency optional

src/wsgi/http.rs
Refers to #203.
I tried to also do ASGI and RSGI but the code was too hard for me to understand in a short time (lots of macros :grinning: ).
=> Log application callable exception traceback on WSGI

granian/_futures.py, src/asgi/callbacks.rs, src/callbacks.rs, src/rsgi/callbacks.rs, src/utils.rs, src/wsgi/http.rs
=> Log application callable exceptions on ASGI and RSGI

Makefile, README.md, granian/_imports.py, granian/cli.py, granian/server.py, pyproject.toml, src/runtime.rs
=> Add process name customization

docs/spec/RSGI.md
=> doc: specify header case in RSGI spec

src/asgi/types.rs
=> Avoid Python calls in ASGI bytes encoding

src/rsgi/types.rs
=> Add missing `Mapping` methods to `RSGIHeaders`

granian/_granian.pyi, granian/asgi.py, granian/rsgi.py, src/asgi/callbacks.rs, src/asgi/http.rs, src/asgi/io.rs, src/asgi/mod.rs, src/asgi/serve.rs, src/asgi/types.rs, src/callbacks.rs, src/conversion.rs, src/rsgi/callbacks.rs, src/rsgi/http.rs, src/rsgi/io.rs, src/rsgi/mod.rs, src/rsgi/serve.rs, src/rsgi/types.rs, src/runtime.rs, src/tcp.rs, src/workers.rs, src/wsgi/serve.rs, src/wsgi/types.rs
=> Move to `pyclass(frozen)`

src/asgi/callbacks.rs, src/asgi/io.rs, src/asgi/types.rs, src/asgi/utils.rs, src/rsgi/io.rs, src/ws.rs, tests/apps/asgi.py, tests/test_ws.py
=> Add support for websockets subprotocols

docs/spec/RSGI.md, src/rsgi/types.rs, tests/test_rsgi.py, tests/test_ws.py
=> Add `RSGIHeaders.get_all`

src/asgi/io.rs
=> Refactor ASGI disconnect flow

src/asgi/io.rs
=> Allow `None` in ASGI ws accept subprotocol

src/callbacks.rs
=> Avoid errors raise on `PyFutureResultSetter` calls

Cargo.lock, Cargo.toml, src/lib.rs
=> Use `jemalloc` allocator on unix platforms

Cargo.lock, Cargo.toml, src/asgi/callbacks.rs, src/asgi/io.rs, src/asgi/mod.rs, src/asgi/serve.rs, src/asgi/utils.rs, src/asyncio.rs, src/callbacks.rs, src/lib.rs, src/rsgi/callbacks.rs, src/rsgi/io.rs, src/rsgi/mod.rs, src/rsgi/serve.rs, src/rsgi/types.rs, src/runtime.rs, src/tcp.rs, src/utils.rs, src/workers.rs, src/wsgi/callbacks.rs, src/wsgi/serve.rs, src/wsgi/types.rs
Close #217 
Depends on: https://github.com/vorner/pyo3-log/pull/45
=> Bump PyO3 to 0.21

granian/_futures.py, src/callbacks.rs
Relates to #252, #279 and possibly #276
=> Review `PyFutureAwaitable` cancellation flow

src/asgi/io.rs
Specifically: avoid Python to wait on file opening and stream creation
=> Enhance ASGI pathsend futures flow

Cargo.lock, Cargo.toml, src/wsgi/callbacks.rs, tests/test_wsgi.py
=> Chain request headers in WSGI protocol

src/wsgi/types.rs
=> Close WSGI iter on errors

src/asgi/io.rs, src/rsgi/io.rs
=> Avoid protocol errors in ASGI and RSGI on ws pong recv

src/wsgi/callbacks.rs
=> Encode path with latin1 in WSGI

granian/wsgi.py, src/conversion.rs, src/wsgi/callbacks.rs, src/wsgi/types.rs
=> Enhance WSGI iterators

Cargo.toml, src/lib.rs
=> Use mimalloc on freebsd

granian/cli.py, granian/errors.py, granian/server.py
Hi,
This PR closes #319
Thanks :)
=> Implemented `--pid-file` to write the process id to a file

granian/wsgi.py, src/asgi/io.rs, src/rsgi/io.rs, src/wsgi/callbacks.rs, src/wsgi/http.rs, src/wsgi/io.rs, src/wsgi/mod.rs, src/wsgi/types.rs
=> Use async channel strategy for WSGI response iteration

docs/spec/RSGI.md, granian/server.py
=> Add `__rsgi_del__` support

src/runtime.rs
=> Hold GIL for drops on futures cancellation

.gitignore
This will prove useful to us Jetbrains users :)
=> chore: add `.idea` folder to `.gitignore`

.github/workflows/benchmarks_ext.yml, benchmarks/README.md, benchmarks/external/tfb.md, benchmarks/external/tfb/loader.py, benchmarks/external/tfb/requirements.txt, benchmarks/templates/external/_tfb_table.tpl, benchmarks/templates/external/tfb.md, benchmarks/templates/main.md
=> Add TFB benchmarks to suite

README.md, granian/cli.py
Quickly change description of regex reload matching as discussed [here](https://github.com/emmett-framework/granian/pull/362#discussion_r1727181591).
=> docs: more explicit description of a reload option

granian/_internal.py, granian/cli.py, granian/server.py
=> Add `--factory` option

src/asgi/io.rs
=> Avoid flow checks in ASGI websocket close

src/asgi/utils.rs
Refers to https://github.com/litestar-org/litestar/issues/3840
=> Avoid `method` item in ASGI ws scope

granian/asgi.py
=> Fix ASGI access logs missing method with websockets

.github/workflows/benchmarks.yml, benchmarks/README.md, benchmarks/benchmarks.py, benchmarks/pyver.md, benchmarks/templates/_helpers.tpl, benchmarks/templates/_vs_ws_table.tpl, benchmarks/templates/vs.md, benchmarks/vs.md, benchmarks/ws/app/asgi.py, benchmarks/ws/app/rsgi.py, benchmarks/ws/benchmark.py
=> Add websockets benchmark

src/asgi/callbacks.rs, src/callbacks.rs, src/rsgi/callbacks.rs
=> Keep asyncio task ref when running callbacks

granian/_granian.pyi, granian/_loops.py, granian/_signals.py, granian/server.py, src/asgi/serve.rs, src/rsgi/serve.rs, src/runtime.rs, src/workers.rs, src/wsgi/serve.rs
=> Avoid to run Python event loop in WSGI

README.md
Fixes https://github.com/emmett-framework/granian/issues/418 as per https://github.com/emmett-framework/granian/issues/418#issuecomment-2503663213
=> Add logging note to README

Cargo.lock, Cargo.toml, build.rs, src/callbacks.rs
=> Add PyPy specific code for `CallbackScheduler`

src/callbacks.rs
=> Fix wrong context in `CallbackSchedulerWaker` calls

granian/_futures.py, src/asgi/callbacks.rs, src/rsgi/callbacks.rs
=> Keep task reference in asyncio task-impl

granian/_futures.py, src/callbacks.rs, tests/apps/asgi.py, tests/test_asgi.py
=> Fix `asyncio` timeouts support in rust task impl

granian/_futures.py, src/callbacks.rs
=> Fix context in rust task impl

Cargo.lock, Cargo.toml, src/workers.rs, src/wsgi/serve.rs
=> Wait for inflight requests to complete on worker shutdown

Cargo.lock, Cargo.toml, src/callbacks.rs
=> Bump PyO3 to 0.24

src/asgi/io.rs, src/rsgi/types.rs, src/wsgi/io.rs
=> Support custom server header

src/asgi/io.rs, src/callbacks.rs, src/runtime.rs
=> Review ASGI I/O flow

README.md, granian/cli.py, granian/server/common.py
attempts to address #529, but it doesn't actually fix it, just mitigates it
=> add reload delay option

src/asgi/utils.rs
=> Keep ASGI scope's `raw_path` untouched

granian/server/mp.py
Tweaks the warning language a bit.
=> Improve WSGI thread count warning

granian/server/mp.py
=> Fix wrong shared socket detach

src/asgi/io.rs
=> Review ASGI send error logging

.github/workflows/build.yml, .github/workflows/release.yml
=> Add (experimental) Linux `i686` and `armv7` wheels

src/asgi/io.rs, src/rsgi/io.rs, src/rsgi/types.rs, src/wsgi/io.rs
=> Review protocols IO with iter responses

src/blocking.rs
SSIA
Discussion and code changes suggested @ https://github.com/PyO3/pyo3/issues/4716
=> Review Python thread state management in blocking pools

src/wsgi/callbacks.rs
=> Strip port from WSGI `REMOTE_ADDR`

granian/server/mp.py
=> Fix event loop init in MP server

Cargo.lock, Cargo.toml, granian/cli.py, granian/server/common.py, granian/server/embed.py, granian/server/mp.py, granian/server/mt.py, src/asgi/serve.rs, src/callbacks.rs, src/files.rs, src/lib.rs, src/rsgi/serve.rs, src/workers.rs, src/wsgi/serve.rs, tests/apps/wsgi.py, tests/conftest.py, tests/test_static_files.py
=> Add support for static files serving

src/asgi/io.rs, src/callbacks.rs
=> Revise ASGI ws accept flow to wait for send

.github/workflows/test.yml, granian/server/common.py, src/asyncio.rs, src/callbacks.rs, tests/test_https.py, tests/test_rsgi.py
=> Fix PyPy builds

src/asgi/io.rs
=> Immediately send ASGI response on event streams

src/workers.rs
Close #548 
Close #568 
Refers to #611
=> Disable connections keepalive on shutdown signal

src/asgi/conversion.rs, src/asgi/errors.rs, src/asgi/io.rs
=> Add descriptions to ASGI flow errors

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/test.yml, Cargo.toml, src/lib.rs
This should make downstream custom builds easier and avoid cases like https://github.com/NixOS/nixpkgs/pull/414234
=> Gate jemalloc behind feature

README.md, granian/utils/proxies.py
=> Add forwarded headers wrappers

granian/server/common.py
=> Keep custom cls if provided for reload filter

src/asgi/io.rs, src/asgi/types.rs
=> Pass relevant close frame in ASGI websockets

README.md
It took me a second to figure out how it work, so I thought I write it down for everybody. ;)
P.S. You're wayyy past the point where Granian would deserve proper docs. 🤓
=> Document trusted_hosts for wrap_[aw]sgi_with_proxy_headers

granian/_internal.py, granian/cli.py
=> Patch python path on CLI for logconfig
