granian/_granian.pyi
granian/wsgi.py
src/wsgi/types.rs
tests/apps/wsgi.py
tests/test_wsgi.py

According to PEP333 `CONTENT_LENGTH` variable is optional but it also says:
> The application should not attempt to read more data than is specified by the CONTENT_LENGTH variable.  
So most implementations assume length is 0 if header is missing.
See for details: https://wsgi.readthedocs.io/en/latest/proposals-2.0.html#unknown-length-wsgi-input
As for the fix itself i'm not sure if is correct. Could just grab length in python?

Add content_length to WSGI environ

---

granian/asgi.py

The unbound methods are stored in the class method _event_handlers, which means we have to provide
the self argument.
Closes #37

Fix: Missing argument for handler in send

---

.github/dependabot.yml

Hopefully this is something useful to help keep dependencies up to date with a little less manual work.  
This enables dependabot for the Cargo and GitHub Actions ecosystems, checking at a monthly interval (configurable).  I don't believe there is anything required besides the inclusion of this file to enable dependabot.

Enables dependabot for Cargo and Actions

---

src/tcp.rs

@gi0baro I have dabbled around in Rust during advent of code a bit, and am looking into using granian for hosting an ASGI app. I'm mostly using Unix sockets so I have been looking into #97 for a bit and reading the code. It seems to me that the Rust `SocketHolder` class is unused since its introduction but I probably missed something.

The socket holder class seems to be unused, remove it

---

README.md
granian/cli.py
granian/log.py
granian/server.py

This PR adds the `--log`/`--no-log` option to CLI and the same argument to the Granian server class. The default value is `enabled`/`True`, so there are no backward compatibility changes. The option/argument simply allows to opt-out from logging to be configured and emit anything.  
Thus, it resolves #101.
Does it look suitable? Don’t hesitate to give any feedback.

Optional logging

---

granian/_futures.py
src/asgi/callbacks.rs
src/asgi/http.rs
src/asgi/io.rs
src/callbacks.rs
src/rsgi/callbacks.rs
src/rsgi/http.rs
src/rsgi/io.rs
src/ws.rs

Async websockets related ehnancements

---

granian/__init__.py

To debug Python ASGI apps it is [common](https://fastapi.tiangolo.com/tutorial/debugging/#debugging) to add some code to your `main.py` file which could look as follows:
```python
if __name__ == "__main__":
import granian
granian.Granian("app.main:app", port=8000, interface="asgi", reload=True).serve()
```
While this works perfectly, one now gets an error when running `mypy`:
```
error: Module "granian" does not explicitly export attribute "Granian"  [attr-defined]
```
See also the [mypy docs on this error](https://mypy.readthedocs.io/en/stable/config_file.html#confval-implicit_reexport).
This PR attempts to fix this error by explicitly re-export the class `Granian` within the `__init__.py` file. (AFAIS FastAPI does it the [same way](https://github.com/tiangolo/fastapi/blob/master/fastapi/ …

Explicitly re-rexport Granian in `__init__.py`

---

src/callbacks.rs
src/runtime.rs

Fallback from `future_into_py_iter` to `future_into_py_futlike` on Linux

---

granian/__main__.py
granian/cli.py
pyproject.toml

As discussed in #261 typer changed the scope of the project and started pulling in other dependencies. 
This pull request changes the dependency used from typer to click. 
The resulting code is a bit more verbose, but the general way of working with it is largely similar. 
I found that there were two features missing in click.
First is no support for enums as choices. But this is easy to work around by supplying a list of choices and in the function itself convert to an enum. 
Second feature missing was the option to show the environment variables for each option. I have added a simple monkey patch to the option function to extend the help text. 
Current state is functional, all option types work and environment variables in general work.. But some more testing is wise.

Rewrite CLI to use click instad of typer

---

granian/cli.py
granian/server.py

Add --reload-interval [seconds] so that Granian can reload slowly for large applications.
I could not locally test this PR

Add --respawn-interval option

---

benchmarks/app/asgi.py
benchmarks/app/rsgi.py
benchmarks/app/wsgi.py
benchmarks/benchmarks.py
benchmarks/templates/vs.md

Add long I/O benchmarks to suite

---

README.md
granian/asgi.py
granian/cli.py
granian/log.py
granian/rsgi.py
granian/server.py
granian/wsgi.py
src/asgi/io.rs
src/asgi/types.rs

Add access log

---

granian/server.py

Hey,
this PR will add slightly more detail to logging on reloads.
Instead of just logging out
```
[INFO] Changes detected, reloading workers..
```
we would give one line for each change like
```
...
[INFO] Started worker-1
[INFO] Started worker-1 runtime-1
[INFO] Changes detected, reloading workers..
[INFO] Modified: /Users/AmonKhavari/granian/a_cool_file.py
[INFO] Modified: /Users/AmonKhavari/granian/another_cool_one.py
[INFO] Added: /Users/AmonKhavari/granian/something
[INFO] Deleted: /Users/AmonKhavari/granian/something_else
[INFO] Stopping worker-1
[INFO] Stopping worker-1 runtime-1
...
```
I personally think it will contribute to better visibility on potential misconfiguration that a user might face.
Especially if #362 goes to master and things might need some configuration.
However, …

feat: more detailed reload logging

---

granian/server.py

Fixes an issue with the reload option: Missing reload handling causes granian with `reload=True` to shutdown instead of respawning workers.

Don't shutdown on reload signal(SIGHUP) when using the reloader option 

---

granian/log.py

Minimal example:
```python
from granian import Granian
Granian(target="", log_dictconfig={"loggers": {}}).serve()
```

fix: KeyError if `_granian` logger is missing in user logging configuration

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/test.yml
Cargo.lock
Cargo.toml
README.md
pyproject.toml
src/asgi/callbacks.rs
src/asgi/io.rs
src/asgi/utils.rs
src/asyncio.rs
src/callbacks.rs
src/conversion.rs
src/rsgi/callbacks.rs
src/rsgi/io.rs
src/rsgi/mod.rs
src/rsgi/types.rs
src/runtime.rs
src/tcp.rs
src/utils.rs
src/wsgi/callbacks.rs
src/wsgi/types.rs

Upgrade to PyO3 0.23

---

granian/_futures.py
granian/_granian.pyi
granian/server.py
src/asgi/io.rs
src/callbacks.rs
src/rsgi/io.rs
src/runtime.rs

Move `_CBScheduler` code to Rust

---

README.md
granian/_futures.py
granian/_imports.py
granian/cli.py
granian/constants.py
granian/server.py
pyproject.toml

Close #466 
Close #467 
I hate `anyio` btw u.u

Add `--task-impl` option

---

src/callbacks.rs

Fix drops in `PyFutureAwaitable` at wrong state path

---

granian/rsgi.py
granian/wsgi.py

Granian is setting REMOTE_ADDR values using SocketAddr::to_string() which uses the format `<host>:<port>` and ipv6 addresses are delimited internally by colons, so the port that needs to be stripped must be taken from the right and there must only be one split done to avoid splitting the ipv6 address.
A possibly simpler alternative is to update Granian's rust wsgi adapter to supply only the client IP address in REMOTE_ADDR so that no parsing needs to be done in the python code.

Fixed incorrect parsing of ipv6 addresses in RSGI/WSGI access logs

---

pyproject.toml

The major release of watchfiles (1.0) should not break anything in granian (main breaking change is the drop of Python 3.8). I'm not sure how I can test it though...

⬆️ Allow watchfiles>1.0 in reload extra

---

pyproject.toml
src/asgi/utils.rs
src/rsgi/types.rs
tests/apps/asgi.py
tests/test_asgi.py

Hello! This is an incomplete attempt at trying to fix the bug that we encountered. I was unable to `cargo build` the project as I'm not familiar with py03. 
What I *think* is happening is that when the path is parsed the `percent_decode` function, it returns a Result type and granian is currently `unwrapping` the result, causing the error to cause the the process to crash. 
If instead of unwrapping it, we return `unwrap_or` with a `Cow<_, str>` with an empty value that should fix it (which is what I've done). Although I suspect this may not be the best way to approach it as there may be other instances of path parsing where we need to decode valid UTF8 but return either an empty string or some HTTP client error? 
Issue: https://github.com/emmett-framework/granian/issues/490

Possible fix for handling invalid http paths

---

Cargo.lock
Cargo.toml
README.md
granian/cli.py
granian/http.py
src/conversion.rs
src/io.rs
src/workers.rs
src/ws.rs

Add request headers read timeout

---

README.md
granian/cli.py
granian/server/common.py

if the worker exits on hot reload, most likely the we don't want the main thread to be interrupted

do not kill main process on worker exit on hot reload

---

README.md
granian/cli.py
tests/test_cli.py

closes #621
I have added a `Duration` parameter that accepts human-readable durations such as `24h`, `6m`, `2s`, or a combination such as  `1m30s`. The default behaviour remains unchanged, so `60` for example will be treated as 60 seconds.
I have changed some of the CLI parameters to be of `Duration` type.
- `--blocking-threads-idle-timeout`
- `--http2-keep-alive-timeout`
- `--workers-lifetime`
- `--workers-kill-timeout`
- `--static-path-expires`

Add human-readable CLI duration arguments

---

granian/__init__.py

I noticed type checkers have trouble with the `granian` package, and it seems to be because of the lack of a `__all__` explicitly defining the exports. We see this is effective as the lint ignores can go away too.

Define __all__ for package init

---

benchmarks/ws/benchmark.py
granian/asgi.py
granian/log.py
granian/rsgi.py
granian/server/common.py
granian/server/embed.py
granian/wsgi.py

When using granian in a production system, we noticed an issue. In the logs, we are printing the `dt_ms` field, and it sometimes reports a clearly incorrect time, such as -15220ms. I took a look at the code and saw you're using `time.time()`. This uses the system clock and is sensitive to spontaneous clock updates outside of our control. Instead, for this use case `time.perf_counter()` should be used, which guarantees a monotonically increasing clock (see https://docs.python.org/3/library/time.html).
I took the liberty of replacing all the usages of `time.time()` with `time.perf_counter()` or `time.monotonic()` where appropriate. Note that in CPython, both `perf_counter` and `monotonic` are actually the same function, but conceptually they are defined differently, so in each case I chose …

Use monotonic time and perf_counter
